### ISSUE TITLE
broken page (https://www.youtube.com/)

### ISSUE THREAD

**Issue by vanos001** [ghostery/ghostery-extension#1360]
for context i use google chrome in ubuntu 22.04
[igmur video](https://imgur.com/a/q6LchjV)
when i turn on ghostery extension the [youtube](youtube.com) goes blank and goes back to normal when i pause it.
please look into it.
feel free to ask for other questions about the issue

**Comment by MrWaggel** [comment]
Having the same issue on Firefox and  Mint 21.2

```
performance.now precision has been modified for compatibility reasons. See https://bugzilla.mozilla.org/show_bug.cgi?id=1756970 for details. bug1842437-www.youtube.com-performance-now-precision.js:18:9
Uncaught SyntaxError: missing } after property list watch:17:1368note: { opened at line 17, column 1325watch:17:1325
Uncaught SyntaxError: missing } after property list watch:19:7437note: { opened at line 17, column 1429watch:17:1429
Uncaught SyntaxError: missing } after property list watch:20:197note: { opened at line 20, column 154watch:20:154
Uncaught TypeError: P(...) is undefined
    ka https://www.youtube.com/s/desktop/18e58bd6/jsbin/scheduler.vflset/scheduler.js:34
    <anonymous> https://www.youtube.com/s/desktop/18e58bd6/jsbin/scheduler.vflset/scheduler.js:35
    <anonymous> https://www.youtube.com/s/desktop/18e58bd6/jsbin/scheduler.vflset/scheduler.js:69
scheduler.js:34:21
Uncaught SyntaxError: missing } after property list watch:20:591note: { opened at line 20, column 548watch:20:548
Uncaught SyntaxError: missing } after property list watch:20:883note: { opened at line 20, column 840watch:20:840
Uncaught SyntaxError: missing } after property list watch:20:7530note: { opened at line 20, column 7487watch:20:7487
Uncaught SyntaxError: missing } after property list watch:20:16703note: { opened at line 20, column 16660watch:20:16660
Uncaught SyntaxError: missing } after property list watch:79:152note: { opened at line 20, column 110523watch:20:110523
Uncaught SyntaxError: missing } after property list watch:80:436note: { opened at line 80, column 154watch:80:154
Uncaught SyntaxError: missing } after property list watch:80:4323note: { opened at line 80, column 4280watch:80:4280
Uncaught TypeError: g.JB(...) is undefined
    hna https://www.youtube.com/s/player/9e328581/player_ias.vflset/en_GB/base.js:1893
    MB https://www.youtube.com/s/player/9e328581/player_ias.vflset/en_GB/base.js:1891
    <anonymous> https://www.youtube.com/s/player/9e328581/player_ias.vflset/en_GB/base.js:8505
    <anonymous> https://www.youtube.com/s/player/9e328581/player_ias.vflset/en_GB/base.js:12629
base.js:1893:26
Uncaught SyntaxError: missing } after property list watch:80:4699note: { opened at line 80, column 4488watch:80:4488
Uncaught SyntaxError: missing } after property list watch:80:4748note: { opened at line 80, column 4705watch:80:4705
Uncaught SyntaxError: missing } after property list watch:82:428note: { opened at line 82, column 154watch:82:154
Uncaught SyntaxError: missing } after property list watch:82:598note: { opened at line 82, column 555watch:82:555
Uncaught SyntaxError: missing } after property list watch:83:326note: { opened at line 83, column 283watch:83:283
Uncaught SyntaxError: missing } after property list watch:83:428note: { opened at line 83, column 385watch:83:385
Uncaught SyntaxError: missing } after property list watch:83:539note: { opened at line 83, column 496watch:83:496
Uncaught SyntaxError: missing } after property list watch:83:12410note: { opened at line 83, column 12367watch:83:12367
Uncaught SyntaxError: missing } after property list watch:83:12515note: { opened at line 83, column 12472watch:83:12472
Uncaught SyntaxError: missing } after property list watch:83:12623note: { opened at line 83, column 12580watch:83:12580
Uncaught TypeError: pl(...) is undefined
    jpa https://www.youtube.com/s/desktop/18e58bd6/jsbin/desktop_polymer_css_polymer_serving_disabled.vflset/desktop_polymer_css_polymer_serving_disabled.js:1419
    yl https://www.youtube.com/s/desktop/18e58bd6/jsbin/desktop_polymer_css_polymer_serving_disabled.vflset/desktop_polymer_css_polymer_serving_disabled.js:1415
    <anonymous> https://www.youtube.com/s/desktop/18e58bd6/jsbin/desktop_polymer_css_polymer_serving_disabled.vflset/desktop_polymer_css_polymer_serving_disabled.js:1855
    <anonymous> https://www.youtube.com/s/desktop/18e58bd6/jsbin/desktop_polymer_css_polymer_serving_disabled.vflset/desktop_polymer_css_polymer_serving_disabled.js:28756
desktop_polymer_css_polymer_serving_disabled.js:1419:24
Uncaught SyntaxError: missing } after property list watch:83:12944note: { opened at line 83, column 12901watch:83:12901
Uncaught SyntaxError: missing } after property list watch:83:13052note: { opened at line 83, column 13009watch:83:13009
Uncaught SyntaxError: missing } after property list watch:83:13160note: { opened at line 83, column 13117watch:83:13117
Uncaught SyntaxError: missing } after property list watch:83:13264note: { opened at line 83, column 13221watch:83:13221
Uncaught SyntaxError: missing } after property list watch:85:197note: { opened at line 85, column 154watch:85:154
Uncaught SyntaxError: missing } after property list watch:85:299note: { opened at line 85, column 256watch:85:256
Uncaught SyntaxError: missing } after property list watch:85:631note: { opened at line 85, column 588watch:85:588
Uncaught SyntaxError: missing } after property list watch:85:734note: { opened at line 85, column 691watch:85:691
Uncaught SyntaxError: missing } after property list watch:85:413892note: { opened at line 85, column 413849watch:85:413849
Uncaught SyntaxError: missing } after property list watch:87:5note: { opened at line 85, column 413952watch:85:413952
Uncaught SyntaxError: missing } after property list watch:87:202note: { opened at line 87, column 159watch:87:159
Uncaught SyntaxError: missing } after property list watch:87:403note: { opened at line 87, column 360watch:87:360
The resource at “https://i.ytimg.com/generate_204” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. watch
The resource at “https://rr6---sn-vg5obxcx-cg0e.googlevideo.com/generate_204” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. watch
The resource at “https://rr6---sn-vg5obxcx-cg0e.googlevideo.com/generate_204?conn2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. watch

```

**Comment by pklinken** [comment]
Same problem here with Firefox 118.0.1, Ghostery 8.11.1, running on OpenSuse Leap

**Comment by tdivis** [comment]
Same here on both Linux and Windows. Same errors in console like MrWaggel. Pausing Ghostery fixes it.

**Comment by vanos001** [comment]
log of chrome Version 118.0.5993.117 using ubuntu 22.04 using ghostery 8.12.2
```
(index):1 Uncaught SyntaxError: Unexpected string (at (index):1:924)
(index):1 Uncaught SyntaxError: Unexpected string (at (index):1:1330)
(index):2 Uncaught SyntaxError: Unexpected string (at (index):2:864)
(index):11 Uncaught SyntaxError: Unexpected string (at (index):11:721)
(index):12 Uncaught SyntaxError: Unexpected string (at (index):12:2129)
(index):12 Uncaught SyntaxError: Unexpected string (at (index):12:2285)
(index):17 Uncaught SyntaxError: Unexpected string (at (index):17:1639)
(index):17 Uncaught SyntaxError: Unexpected string (at (index):17:1743)
(index):20 Uncaught SyntaxError: Unexpected string (at (index):20:721)
scheduler.js:34 Uncaught TypeError: Cannot read properties of undefined (reading 'web_emulated_idle_callback_delay')
    at ka (scheduler.js:34:45)
    at scheduler.js:35:9
    at scheduler.js:69:506
ka @ scheduler.js:34
(anonymous) @ scheduler.js:35
(anonymous) @ scheduler.js:69
(index):20 Uncaught SyntaxError: Unexpected string (at (index):20:1377)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:850)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:1142)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:7574)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:7676)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:7787)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:29854)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:29957)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:30062)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:30170)
desktop_polymer_enable_wil_icons.js:1419 Uncaught TypeError: Cannot read properties of undefined (reading 'max_body_size_to_compress')
    at jpa (desktop_polymer_enable_wil_icons.js:1419:49)
    at yl (desktop_polymer_enable_wil_icons.js:1415:20)
    at desktop_polymer_enable_wil_icons.js:1855:10
    at desktop_polymer_enable_wil_icons.js:29607:483
jpa @ desktop_polymer_enable_wil_icons.js:1419
yl @ desktop_polymer_enable_wil_icons.js:1415
(anonymous) @ desktop_polymer_enable_wil_icons.js:1855
(anonymous) @ desktop_polymer_enable_wil_icons.js:29607
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:30467)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:30575)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:30683)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:30787)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:30889)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:31221)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:31324)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:530083)
(index):21 Uncaught SyntaxError: Unexpected string (at (index):21:530186)
(index):23 Uncaught SyntaxError: Unexpected string (at (index):23:4770)
(index):23 Uncaught SyntaxError: Unexpected string (at (index):23:4873)
(index):23 Uncaught SyntaxError: Unexpected string (at (index):23:5018)
www.youtube.com/:1 The resource https://i.ytimg.com/generate_204 was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by chrmod** [comment]
Thank you all for the reports. 
The problem comes from new kinds of rules that are used to provide ad-blocking on youtube. Ghostery adblocker engine does not handle arguments to some rules properly and in an edge case it can break websites. Sadly this happened on youtube. 
We found the problematic rules and removed them until we support them correctly.
A proper fix should come very soon - please stay tuned.

**Comment by vanos001** [comment]
thnx boss for resolving the issue
