### ISSUE TITLE
Filename too long on Windows

### ISSUE THREAD

**Issue by GRadziejewski** [ghostery/ghostery-extension#1751]
I'm having trouble building a v10 build for Firefox Android, on Windows.

My default path: `C:\GIT\ghostery-extension\extension-manifest-v3`

After `npm run build firefox` I have an error:
```
Filename too long: C:/GIT/ghostery-extension/npm/@ghostery/trackers-preview/src/background/trackers-preview-generated.js (101) (pass --no-filename-limit to disable)
✓ built in 4.86s
file:///C:/GIT/ghostery-extension/extension-manifest-v3/scripts/build.js:291
            throw new Error(`Filename too long: ${path} (${path.length}) (pass --no-filename-limit to disable)`);
                  ^

Error: Filename too long: C:/GIT/ghostery-extension/npm/@ghostery/trackers-preview/src/background/trackers-preview-generated.js (101) (pass --no-filename-limit to disable)
    at sanitizeFileName (file:///C:/GIT/ghostery-extension/extension-manifest-v3/scripts/build.js:291:19)
    at Chunk.getPreserveModulesChunkNameFromModule (file:///C:/GIT/ghostery-extension/node_modules/rollup/dist/es/shared/node-entry.js:16400:29)
    at Chunk.assignFacadeName (file:///C:/GIT/ghostery-extension/node_modules/rollup/dist/es/shared/node-entry.js:16132:28)
    at Chunk.generateFacades (file:///C:/GIT/ghostery-extension/node_modules/rollup/dist/es/shared/node-entry.js:15908:26)
    at Bundle.generateChunks (file:///C:/GIT/ghostery-extension/node_modules/rollup/dist/es/shared/node-entry.js:18017:35)
    at async Bundle.generate (file:///C:/GIT/ghostery-extension/node_modules/rollup/dist/es/shared/node-entry.js:17913:28)
    at async file:///C:/GIT/ghostery-extension/node_modules/rollup/dist/es/shared/node-entry.js:26785:27
    at async catchUnfinishedHookActions (file:///C:/GIT/ghostery-extension/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at async build (file:///C:/GIT/ghostery-extension/node_modules/vite/dist/node/chunks/dep-52909643.js:48082:22)

Node.js v20.6.1
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: @ghostery/extension-manifest-v3@10.3.13
npm ERR!   at location: C:\GIT\ghostery-extension\extension-manifest-v3
```

**Comment by philipp-classen** [comment]
Please try this to disable the check:
```
npm run build firefox -- --no-filename-limit
```

**Comment by GRadziejewski** [comment]
It helps. Closing.
